### ISSUE TITLE
add function does not process weeks

### ISSUE THREAD

**Issue by pixelshaded** [JerrySievert/cromagjs#1]
The generic add function docs say that weeks is a key for the offset object, but the source does not process that key.

``` javascript
polyfill('add', function (obj) {
        if (obj.milliseconds !== undefined) {
            this.setMilliseconds(this.getMilliseconds() + obj.milliseconds);
        }
        if (obj.seconds !== undefined) {
            this.setSeconds(this.getSeconds() + obj.seconds);
        }
        if (obj.minutes !== undefined) {
            this.setMinutes(this.getMinutes() + obj.minutes);
        }
        if (obj.hours !== undefined) {
            this.setHours(this.getHours() + obj.hours);
        }
        if (obj.days !== undefined) {
            this.setDate(this.getDate() + obj.days);
        }
        if (obj.months !== undefined) {
            this.setMonth(this.getMonth() + obj.months);
        }
        if (obj.years !== undefined) {
            this.setFullYear(this.getFullYear() + obj.years);
        }
        return this;
    });
```

and addWeeks just uses days key

``` javascript
polyfill('addWeeks', function (weeks) {
        return this.add({ days: (weeks * 7) });
    });
```

The offset object is semantically awesome for config options. Weeks should be included.

**Comment by JerrySievert** [comment]
is there some reason why you object to addWeeks using the days keys (with weeks \* 7)?

looking at the weeks now.

**Comment by pixelshaded** [comment]
I think I did a poor job of explaining. Lets say I want to create a config file where a user can define a lifespan.

``` javascript
//this is in a separate config file somewhere
var config = { "lifespan" : { "days" : 14 } };

//this is somewhere else in the app
var created = new Cromag();
var expires = created.add(config.lifespan);
```

This is essentially two weeks. However the add function does not support the key/property 'weeks'. If I were to do this code instead:

``` javascript
//this is in a separate config file somewhere
var config = { "lifespan" : { "weeks" : 2 } };

//this is somewhere else in the app
var created = new Cromag();
var expires = created.add(config.lifespan);
```

Weeks would be ignored and expires would be equal to created.

**Comment by pixelshaded** [comment]
In other words, addWeeks is not a problem. It only takes one parameter and gives the result you would expect. Add however takes an object with multiple keys and is great because I can define a length of time like so:

``` javascript
{ time : { 'months' : 2, 'days' 10, 'minutes' : 10 }}. 
```

This is so much easier to read than having to convert the entire thing to milliseconds for the default Date object. 

``` javascript
{ time : 2629800000 + 864000000 + 600000 }
```

My only complaint is that it doesn't support the key 'weeks', especially when the [documentation](https://github.com/JerrySievert/cromagjs#add) says it should.

**Comment by JerrySievert** [comment]
fixed and new version released on npm.

thanks for the bug report!
